#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    bgndSounds.py
# @author  AutoGenerated
# @date    04/27/2017
#
# @note    Open Pinball Project
# @note    Copyright 2015, Hugh Spahr
#
# @brief This is an enumeration of all the background sounds.

#===============================================================================

## Background sounds enumeration.
#  Contains an entry for each background sound
class BgndMusic():
    def __init__(self):
        pass

    BGND_JUMP                                = 0
    BGND_YOUREALLYGOTME                      = 1
    BGND_UNCHAINED                           = 2
    BGND_PANAMA                              = 3
    BGND_HOTFORTEACHER                       = 4
    BGND_DROPDEADLEGS                        = 5
    BGND_BESTOFBOTHWORLDS                    = 6
    BGND_TOPOFTHEWORLD                       = 7
    BGND_RIGHTNOW                            = 8
    BGND_POUNDCAKE                           = 9
    BGND_FEELSSOGOOD                         = 10
    BGND_CABOWABO                            = 11
    BGND_CALIFORNIAGIRLS                     = 12
    BGND_GETUP                               = 13
    BGND_GOODENOUGH                          = 14
    BGND_ICECREAMMAN                         = 15
    BGND_ERUPTION                            = 16

    ## Background sound file list
    # Indexed into using the [BgndMusic](@ref bgndSounds.BgndMusic) class
    BGND_MUSIC_FILES = ["copyrighted/Jump.mp3", "copyrighted/YouReallyGotMe.mp3", "copyrighted/Unchained.mp3", "copyrighted/Panama.mp3", "copyrighted/HotForTeacher.mp3", 
        "copyrighted/DropDeadLegs.mp3", "copyrighted/BestOfBothWorlds.mp3", "copyrighted/TopOfTheWorld.mp3", "copyrighted/RightNow.mp3", "copyrighted/Poundcake.mp3", 
        "copyrighted/FeelsSoGood.mp3", "copyrighted/CaboWabo.mp3", "copyrighted/CaliforniaGirls.mp3", "copyrighted/GetUp.mp3", "copyrighted/GoodEnough.mp3", 
        "copyrighted/IceCreamMan.mp3", "copyrighted/Eruption.mp3"]

