#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    images.py
# @author  AutoGenerated
# @date    05/06/2017
#
# @note    Open Pinball Project
# @note    Copyright 2015, Hugh Spahr
#
# @brief This is an enumeration of all the images.

#===============================================================================

## Images enumeration.
#  Contains an entry for each image

class Images():
    def __init__(self):
        pass

    IMAGE_JUMP           = 0
    IMAGE_YOUREALLYGOTME = 1
    IMAGE_UNCHAINED      = 2
    IMAGE_PANAMA         = 3
    IMAGE_HOTFORTEACHER  = 4
    IMAGE_DROPDEADLEGS   = 5
    IMAGE_BESTOFBOTHWORLDS = 6
    IMAGE_TOPOFTHEWORLD  = 7
    IMAGE_RIGHTNOW       = 8
    IMAGE_POUNDCAKE      = 9
    IMAGE_FEELSSOGOOD    = 10
    IMAGE_CABOWABO       = 11
    IMAGE_ATTRACTMODE    = 12
    IMAGE_WIZARDMODE     = 13

    ## Background images
    # Indexed into using the [Images](@ref images.Images) class
    BGND_GRAPHIC_FILES = ["graphics/jump.jpg", "graphics/you_really_got_me.jpg", "graphics/unchained.jpg", "graphics/panama.jpg", "graphics/hot_for_teacher.jpg", 
        "graphics/drop_dead_legs.jpg", "graphics/best_of_both_worlds.jpg", "graphics/top_of_the_world.jpg", "graphics/right_now.jpg", "graphics/poundcake.jpg", 
        "graphics/feels_so_good.jpg", "graphics/cabo_wabo.jpg", "graphics/attract_mode.jpg", "graphics/wizard_mode.jpg"]

