#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    imageChains.py
# @author  AutoGenerated
# @date    05/06/2017
#
# @note    Open Pinball Project
# @note    Copyright 2015, Hugh Spahr
#
# @brief These are the image chains.  It includes chains to automatically play
#    a set of images with delays in between.

#===============================================================================

from images import Images

## Image chains class.
#
#  Contains all the image chains that are specific to this set of pinball rules.
#
#  Each image chain group contains the image to play, the command, and the
#  parameter to the command.

class ImageChains():    # Image chain commands
    WAIT = 0
    REPEAT = 1
    END_CHAIN = 2

    IMAGE_OFFSET = 0
    CH_CMD_OFFSET = 1
    PARAM_OFFSET = 2

    ## Image Chain ImageCh_Attract
    #    - Groups have image name then WAIT command
    #    - Chain ends with REPEAT if desired
    ImageCh_Attract = [
        [Images.IMAGE_ATTRACTMODE,  WAIT, 30000],
        [Images.IMAGE_ATTRACTMODE,  WAIT, 30000],
        [0, REPEAT, 0] ]

