#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    inpBitNames.py
# @author  AutoGenerated
# @date    04/27/2017
#
# @note    Open Pinball Project
# @note    Copyright 2014, Hugh Spahr
#
# @brief These are the input bit names.  It has a bitmask for each input.

#===============================================================================

import rs232Intf

## Input bit name enumeration.
#  Contains a bit mask for each input.  Can also contain bitfield masks.
#  Top most nibble contains the index of the input card base 0.
class InpBitNames:
    def __init__(self):
        pass

    MTRX_INP_DROP_TRGT_5X                            = 0x02800001
    MTRX_INP_DROP_TRGT_3X                            = 0x02800002
    MTRX_INP_DROP_TRGT_2X                            = 0x02800004
    MTRX_INP_DROP_TRGT_1ST                           = 0x02800008
    MTRX_INP_SUPER_STAR_TRGT                         = 0x02800010
    MTRX_INP_TILT1                                   = 0x02800040
    MTRX_INP_OUTHOLE                                 = 0x02800080
    MTRX_INP_SPINNER                                 = 0x02820001
    MTRX_INP_LFT_TRGT                                = 0x02820004
    MTRX_INP_RGHT_OUTLN                              = 0x02820008
    MTRX_INP_RGHT_INLN                               = 0x02820010
    MTRX_INP_LFT_INLN                                = 0x02820020
    MTRX_INP_LFT_OUTLN                               = 0x02820040
    MTRX_INP_SAUCER                                  = 0x02820080
    MTRX_INP_D2_TRGT                                 = 0x02830008
    MTRX_INP_I_TRGT                                  = 0x02830010
    MTRX_INP_V_TRGT                                  = 0x02830020
    MTRX_INP_A_TRGT                                  = 0x02830040
    MTRX_INP_D_TRGT                                  = 0x02830080
    MTRX_INP_REBND                                   = 0x02840002
    MTRX_INP_PANAMA_ROLL                             = 0x02840004
    MTRX_INP_RGHT_SLING                              = 0x02840008
    MTRX_INP_LFT_SLING                               = 0x02840010
    MTRX_INP_TOP_POP                                 = 0x02840020
    MTRX_INP_BTM_POP                                 = 0x02840040
    MTRX_INP_LFT_POP                                 = 0x02840080
    MTRX_INP_CRDT_RST                                = 0x03800020
    MTRX_INP_TILT2                                   = 0x03800040
    MTRX_INP_COIN3                                   = 0x03810001
    MTRX_INP_COIN1                                   = 0x03810002
    MTRX_INP_COIN2                                   = 0x03810004
    MTRX_INP_SLAM                                    = 0x03810080


    ## Input board bit names
    # Indexed into using the [InpBitNames](@ref inpBitNames.InpBitNames) class
    INP_BRD_BIT_NAMES = [ [ ],
        [ ],
        [ ],
        [ ] ]

    ## Input board configuration
    INP_BRD_CFG = [ [ ],
        [ ],
        [ ],
        [ ] ]


    ## Input board matrix bit names
    # Indexed into using the [InpBitNames](@ref inpBitNames.InpBitNames) class
    INP_BRD_MTRX_BIT_NAMES = [ [ ],
        [ ],
        ["5xDrop", "3xDrop", "2xDrop", "1stDrop",
        "SuperStar", "Unused", "Tilt1", "Outhole",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Spinner", "Unused", "LftTrgt", "RghtOutln",
        "RghtInln", "LftInln", "LftOutln", "Saucer",
        "Unused", "Unused", "Unused", "D2Trgt",
        "ITrgt", "VTrgt", "ATrgt", "DTrgt",
        "Unused", "Rbnd", "PanamaRoll", "RghtSling",
        "LftSling", "TopPop", "BtmPop", "LftPop",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused"],
        ["Unused", "Unused", "Unused", "Unused",
        "Unused", "CrdtRst", "Tilt2", "Unused",
        "Coin3", "Coin1", "Coin2", "Unused",
        "Unused", "Unused", "Unused", "Slam",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused"] ]

