#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    ledBitNames.py
# @author  AutoGenerated
# @date    05/31/2017
#
# @note    Open Pinball Project
# @note    Copyright 2014, Hugh Spahr
#
# @brief These are the LED bit names.  It has a bitmask for each LED.

#===============================================================================

## LED bit name enumeration.
#  Contains a bit mask for each LED.  Can also contain bitfield masks.
#  Top most nibble contains the index of the LED card base 0.
class LedBitNames:
    def __init__(self):
        pass

    LED0W0_ALL_BITS_MSK              = 0x000000ff
    LED0W1_ALL_BITS_MSK              = 0x000100ff
    LED0W2_ALL_BITS_MSK              = 0x000200ff
    LED0W3_ALL_BITS_MSK              = 0x000300ff
    LED_CRD0_LIST_BITS_MSK           = 0xffffffff
    LED_CREDIT_IND                   = 0x00000001
    LED_RGHT_CAR_BLOCK               = 0x00000008
    LED_ROTH                         = 0x00000010
    LED_SPCL_DROP_TRGT               = 0x00000020
    LED_ROCKER_R2                    = 0x00000040
    LED_XTRA_BALL_DROP               = 0x00000080
    LED_RGHT_HDLGHT                  = 0x00010001
    LED_SHOOT_AGAIN                  = 0x00010002
    LED_1984_9                       = 0x00010004
    LED_4X_BONUS                     = 0x00010008
    LED_ROCKER_O                     = 0x00010010
    LED_DAVID_V                      = 0x00010020
    LED_EDDIE_D2                     = 0x00010040
    LED_EDDIE_E2                     = 0x00020001
    LED_2X_BONUS                     = 0x00020002
    LED_ALEX_E                       = 0x00020010
    LED_DAVID_D2                     = 0x00020020
    LED_DAVID_D1                     = 0x00020040
    LED_ROCKER_K                     = 0x00020080
    LED_EDDIE_E1                     = 0x00030001
    LED_1984_4                       = 0x00030002
    LED_20K_DROP                     = 0x00030004
    LED_ALEX_A                       = 0x00030008
    LED_3X_BONUS                     = 0x00030010
    LED_1984_8                       = 0x00030040
    LED_ROCKER_R1                    = 0x00030080
    LED1W0_ALL_BITS_MSK              = 0x010000ff
    LED1W1_ALL_BITS_MSK              = 0x010100ff
    LED_CRD1_LIST_BITS_MSK           = 0x0000ffff
    LED_DAVID_I                      = 0x01000001
    LED_ALEX_L                       = 0x01000002
    LED_1984_1                       = 0x01000004
    LED_EDDIE_I                      = 0x01000008
    LED_CTR_CAR_BLOCK                = 0x01000010
    LED_SPINNER                      = 0x01000040
    LED_ROCKER_C                     = 0x01000080
    LED_DAVID_A                      = 0x01010001
    LED_LFT_CAR_BLOCK                = 0x01010002
    LED_BLW_SAUCER                   = 0x01010004
    LED_ALEX_X                       = 0x01010010
    LED_LFT_HDLGHT                   = 0x01010020
    LED_EDDIE_D1                     = 0x01010040
    LED_ROCKER_E                     = 0x01010080

    LED_CREDIT_IND_CRD0MSK                           = 0x00000001
    LED_RGHT_CAR_BLOCK_CRD0MSK                       = 0x00000008
    LED_ROTH_CRD0MSK                                 = 0x00000010
    LED_SPCL_DROP_TRGT_CRD0MSK                       = 0x00000020
    LED_ROCKER_R2_CRD0MSK                            = 0x00000040
    LED_XTRA_BALL_DROP_CRD0MSK                       = 0x00000080
    LED_RGHT_HDLGHT_CRD0MSK                          = 0x00000100
    LED_SHOOT_AGAIN_CRD0MSK                          = 0x00000200
    LED_1984_9_CRD0MSK                               = 0x00000400
    LED_4X_BONUS_CRD0MSK                             = 0x00000800
    LED_ROCKER_O_CRD0MSK                             = 0x00001000
    LED_DAVID_V_CRD0MSK                              = 0x00002000
    LED_EDDIE_D2_CRD0MSK                             = 0x00004000
    LED_EDDIE_E2_CRD0MSK                             = 0x00010000
    LED_2X_BONUS_CRD0MSK                             = 0x00020000
    LED_ALEX_E_CRD0MSK                               = 0x00100000
    LED_DAVID_D2_CRD0MSK                             = 0x00200000
    LED_DAVID_D1_CRD0MSK                             = 0x00400000
    LED_ROCKER_K_CRD0MSK                             = 0x00800000
    LED_EDDIE_E1_CRD0MSK                             = 0x01000000
    LED_1984_4_CRD0MSK                               = 0x02000000
    LED_20K_DROP_CRD0MSK                             = 0x04000000
    LED_ALEX_A_CRD0MSK                               = 0x08000000
    LED_3X_BONUS_CRD0MSK                             = 0x10000000
    LED_1984_8_CRD0MSK                               = 0x40000000
    LED_ROCKER_R1_CRD0MSK                            = 0x80000000
    LED_DAVID_I_CRD1MSK                              = 0x00000001
    LED_ALEX_L_CRD1MSK                               = 0x00000002
    LED_1984_1_CRD1MSK                               = 0x00000004
    LED_EDDIE_I_CRD1MSK                              = 0x00000008
    LED_CTR_CAR_BLOCK_CRD1MSK                        = 0x00000010
    LED_SPINNER_CRD1MSK                              = 0x00000040
    LED_ROCKER_C_CRD1MSK                             = 0x00000080
    LED_DAVID_A_CRD1MSK                              = 0x00000100
    LED_LFT_CAR_BLOCK_CRD1MSK                        = 0x00000200
    LED_BLW_SAUCER_CRD1MSK                           = 0x00000400
    LED_ALEX_X_CRD1MSK                               = 0x00001000
    LED_LFT_HDLGHT_CRD1MSK                           = 0x00002000
    LED_EDDIE_D1_CRD1MSK                             = 0x00004000
    LED_ROCKER_E_CRD1MSK                             = 0x00008000

    ## LED board bit names
    # Indexed into using the [LedBitNames](@ref ledBitNames.LedBitNames) class
    LED_BRD_BIT_NAMES = [ ["CreditInd", "Unused", "Unused", "RghtCarBlock",
        "Roth", "SpclDropTrgt", "RockerR2", "XtraBallDrop",
        "RghtHdlght", "ShootAgain", "1984_9", "4xBonus",
        "RockerO", "DavidV", "EddieD2", "Unused",
        "EddieE2", "2xBonus", "Unused", "Unused",
        "AlexE", "DavidD2", "DavidD1", "RockerK",
        "EddieE1", "1984_4", "20KDrop", "AlexA",
        "3xBonus", "Unused", "1984_8", "RockerR1"],
        ["DavidI", "AlexL", "1984_1", "EddieI",
        "CtrCarBlock", "Unused", "Spinner", "RockerC",
        "DavidA", "LftCarBlock", "BlwSaucer", "Unused",
        "AlexX", "LftHdlght", "EddieD1", "RockerE",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused"],
        [ ],
        [ ] ]

