#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    ledChains.py
# @author  AutoGenerated
# @date    04/27/2017
#
# @note    Open Pinball Project
# @note    Copyright 2015, Hugh Spahr
#
# @brief These are the LED chains.  It includes chains to automatically change
#    LEDs depending on the state.

#===============================================================================

from ledBitNames import LedBitNames

## LED chains class.
#
#  Contains all the LED chains that are specific this this set of pinball rules.
class LedChains():
    def __init__(self):
        pass

    # LED chain commands
    WAIT = 0
    REPEAT = 1
    END_CHAIN = 2

    MASK_OFFSET = 0
    CHAIN_OFFSET = 1

    # Offsets into sublist
    CH_LED_BITS_OFFSET = 0
    CH_CMD_OFFSET = 1
    PARAM_OFFSET = 2

    ## LED Chain LedCh_Attract
    #    - First entry is LED mask
    #    - Next groups have a bitfield of LEDs to change and command
    LedCh_Attract = [
        # LED0W0_ALL_BITS_MSK | LED0W1_ALL_BITS_MSK | LED0W2_ALL_BITS_MSK | LED0W3_ALL_BITS_MSK, LED1W0_ALL_BITS_MSK | LED1W1_ALL_BITS_MSK, 0, 0
        [ 0xffffffff, 0x0000ffff, 0, 0 ],
        [ # LED_SHOOT_AGAIN, 0, 0, 0
          [ [ 0x00000200, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS, 0, 0, 0
          [ [ 0x00020200, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_3X_BONUS, 0, 0, 0
          [ [ 0x10000200, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_4X_BONUS, 0, 0, 0
          [ [ 0x00000a00, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_3X_BONUS, 0, 0, 0
          [ [ 0x10000200, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS, 0, 0, 0
          [ [ 0x00020200, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS, 0, 0, 0
          [ [ 0x10020a00, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN, 0, 0, 0
          [ [ 0x00000200, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS, 0, 0, 0
          [ [ 0x10020a00, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN, 0, 0, 0
          [ [ 0x00000200, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS, 0, 0, 0
          [ [ 0x10020a00, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN, 0, 0, 0
          [ [ 0x00000200, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1, 0, 0, 0
          [ [ 0x11020a00, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_ALEX_A, 0, 0, 0
          [ [ 0x19020a00, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_ALEX_A, LED_EDDIE_D1, 0, 0
          [ [ 0x19020a00, 0x00004000, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_ALEX_A, LED_EDDIE_D1 | LED_ALEX_L, 0, 0
          [ [ 0x19020a00, 0x00004002, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_ALEX_A, LED_EDDIE_D1 | LED_ALEX_L, 0, 0
          [ [ 0x19024a00, 0x00004002, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_ALEX_A | LED_ALEX_E, LED_EDDIE_D1 | LED_ALEX_L, 0, 0
          [ [ 0x19124a00, 0x00004002, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_ALEX_A | LED_ALEX_E, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L, 0, 0
          [ [ 0x19124a00, 0x0000400a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_ALEX_A | LED_ALEX_E, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X, 0, 0
          [ [ 0x19124a00, 0x0000500a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X, 0, 0
          [ [ 0x19134a00, 0x0000500a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS, 0, 0, 0
          [ [ 0x10020a00, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X, 0, 0
          [ [ 0x19134a00, 0x0000500a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS, 0, 0, 0
          [ [ 0x10020a00, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X, 0, 0
          [ [ 0x19134a00, 0x0000500a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS, 0, 0, 0
          [ [ 0x10020a00, 0, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X, 0, 0
          [ [ 0x19134a00, 0x0000500a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X, 0, 0
          [ [ 0x19534a00, 0x0000500a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A, 0, 0
          [ [ 0x19134a00, 0x0000510a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_V, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X, 0, 0
          [ [ 0x19136a00, 0x0000500a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_I, 0, 0
          [ [ 0x19134a00, 0x0000500b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D2, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X, 0, 0
          [ [ 0x19334a00, 0x0000500a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_I, 0, 0
          [ [ 0x19134a00, 0x0000500b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_V, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X, 0, 0
          [ [ 0x19136a00, 0x0000500a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A, 0, 0
          [ [ 0x19134a00, 0x0000510a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X, 0, 0
          [ [ 0x19534a00, 0x0000500a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I, 0, 0
          [ [ 0x19736a10, 0x0000510b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X, 0, 0
          [ [ 0x19134a00, 0x0000500a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I, 0, 0
          [ [ 0x19736a10, 0x0000510b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X, 0, 0
          [ [ 0x19134a00, 0x0000500a, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I, 0, 0
          [ [ 0x19736a10, 0x0000510b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH | LED_ROCKER_R1, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I, 0, 0
          [ [ 0x99736a10, 0x0000510b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH | LED_ROCKER_O, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I, 0, 0
          [ [ 0x19737a10, 0x0000510b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I | LED_ROCKER_C, 0, 0
          [ [ 0x19736a10, 0x0000518b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH | LED_ROCKER_K, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I, 0, 0
          [ [ 0x19f36a10, 0x0000510b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I | LED_ROCKER_E, 0, 0
          [ [ 0x19736a10, 0x0000d10b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH | LED_ROCKER_R2, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I, 0, 0
          [ [ 0x19736a50, 0x0000510b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I | LED_ROCKER_E, 0, 0
          [ [ 0x19736a10, 0x0000d10b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH | LED_ROCKER_K, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I, 0, 0
          [ [ 0x19f36a10, 0x0000510b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I | LED_ROCKER_C, 0, 0
          [ [ 0x19736a10, 0x0000518b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH | LED_ROCKER_O, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I, 0, 0
          [ [ 0x19737a10, 0x0000510b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH | LED_ROCKER_R1, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I, 0, 0
          [ [ 0x99736a10, 0x0000510b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH | LED_ROCKER_R1 | LED_ROCKER_O | LED_ROCKER_K | LED_ROCKER_R2, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I | LED_ROCKER_C | LED_ROCKER_E, 0, 0
          [ [ 0x99f37a50, 0x0000d18b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I, 0, 0
          [ [ 0x19736a10, 0x0000510b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH | LED_ROCKER_R1 | LED_ROCKER_O | LED_ROCKER_K | LED_ROCKER_R2, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I | LED_ROCKER_C | LED_ROCKER_E, 0, 0
          [ [ 0x99f37a50, 0x0000d18b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I, 0, 0
          [ [ 0x19736a10, 0x0000510b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH | LED_ROCKER_R1 | LED_ROCKER_O | LED_ROCKER_K | LED_ROCKER_R2, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I | LED_ROCKER_C | LED_ROCKER_E, 0, 0
          [ [ 0x99f37a50, 0x0000d18b, 0, 0 ],  WAIT, 100],
          # LED_SHOOT_AGAIN | LED_2X_BONUS | LED_3X_BONUS | LED_4X_BONUS | LED_EDDIE_E1 | LED_EDDIE_D2 | LED_EDDIE_E2 | LED_ALEX_A | LED_ALEX_E | LED_DAVID_D1 | LED_DAVID_V | LED_DAVID_D2 | LED_ROTH, LED_EDDIE_D1 | LED_EDDIE_I | LED_ALEX_L | LED_ALEX_X | LED_DAVID_A | LED_DAVID_I, 0, 0
          [ [ 0x19736a10, 0x0000510b, 0, 0 ],  WAIT, 100],
          # 0, 0, 0, 0
          [ [ 0, 0, 0, 0 ],  WAIT, 500],
          # LED0W0_ALL_BITS_MSK | LED0W1_ALL_BITS_MSK | LED0W2_ALL_BITS_MSK | LED0W3_ALL_BITS_MSK, LED1W0_ALL_BITS_MSK | LED1W1_ALL_BITS_MSK, 0, 0
          [ [ 0xffffffff, 0x0000ffff, 0, 0 ],  WAIT, 500],
          # 0, 0, 0, 0
          [ [ 0, 0, 0, 0 ],  WAIT, 500],
          # LED0W0_ALL_BITS_MSK | LED0W1_ALL_BITS_MSK | LED0W2_ALL_BITS_MSK | LED0W3_ALL_BITS_MSK, LED1W0_ALL_BITS_MSK | LED1W1_ALL_BITS_MSK, 0, 0
          [ [ 0xffffffff, 0x0000ffff, 0, 0 ],  WAIT, 500],
          # 0, 0, 0, 0
          [ [ 0, 0, 0, 0 ],  WAIT, 500],
          # LED0W0_ALL_BITS_MSK | LED0W1_ALL_BITS_MSK | LED0W2_ALL_BITS_MSK | LED0W3_ALL_BITS_MSK, LED1W0_ALL_BITS_MSK | LED1W1_ALL_BITS_MSK, 0, 0
          [ [ 0xffffffff, 0x0000ffff, 0, 0 ],  WAIT, 500],
          # 0, 0, 0, 0
          [ [ 0, 0, 0, 0 ],  WAIT, 500],
          # 0, 0, 0, 0
          [ [ 0, 0, 0, 0 ], REPEAT, 0] ] ]

    ## LED Chain LedCh_Tilt
    #    - First entry is LED mask
    #    - Next groups have a bitfield of LEDs to change and command
    LedCh_Tilt = [
        # LED_SHOOT_AGAIN, 0, 0, 0
        [ 0x00000200, 0, 0, 0 ],
        [ # 0, 0, 0, 0
          [ [ 0, 0, 0, 0 ], END_CHAIN, 0] ] ]

