#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    rulesFunc.py
# @author  AutoGenerated
# @date    04/27/2017
#
# @note    Open Pinball Project
# @note    Copyright 2014, Hugh Spahr
#
# @brief These are the rules function names.  The rules functions can call
#    other rules functions, or be called in chains.  The generator saves
#    the file as rulesFunc.py.gen.  The pinball framework uses rulesFunc.py.
#    This insures a newly generated file won't accidentally overwrite a
#    user modified rules file.

#===============================================================================

from VH.inpBitNames import InpBitNames
from VH.solBitNames import SolBitNames
from VH.ledBitNames import LedBitNames
from VH.timers import Timers
from VH.rulesData import RulesData
from VH.sounds import Sounds
from VH.bgndSounds import BgndMusic
from VH.states import State
from VH.images import Images
from dispConstIntf import DispConst
from VH.customFunc import CustomFunc

## Rules functions class.
#  Contains all the rules that are specific this this set of pinball rules.

class RulesFunc:
    ## Initialize rulesFuncs class
    #
    #  Initialize rules functions class
    #
    #  @param  self          [in]   Object reference
    #  @param  gameData      [in]   Object reference
    #  @return None
    def __init__(self, gameData):
        RulesFunc.GameData = gameData
        RulesFunc.CustomFunc = CustomFunc(gameData)

    ## Function Proc_Tilt
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Tilt(self):
        pass

    ## Function Proc_Flipper
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Flipper(self):
        pass

    ## Function Proc_Inlane
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Inlane(self):
        pass

    ## Function Proc_Targets
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Targets(self):
        pass

    ## Function Proc_Kickout_Hole
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Kickout_Hole(self):
        pass

    ## Function Proc_Ball_Drain
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Ball_Drain(self):
        pass

    ## Function Proc_Tilt_Init
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Tilt_Init(self):
        pass

    ## Function Proc_Tilt_State
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Tilt_State(self):
        pass

    ## Function Proc_Init
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Init(self):
        RulesFunc.GameData.StdFuncs.Restore_Input_Cfg()
        RulesFunc.GameData.gameMode = State.MODE_ATTRACT

    ## Function Proc_Attract_Init
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Attract_Init(self):
        RulesFunc.GameData.StdFuncs.Disable_Solenoids()
        RulesFunc.GameData.creditBallNumDisp = RulesFunc.GameData.credits
        RulesFunc.CustomFunc.init_attract_mode()

    ## Function Proc_Add_Coin
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Add_Coin(self):
        pass

    ## Function Proc_Press_Start
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Press_Start(self):
        pass

    ## Function Proc_Start_and_Coin
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Start_and_Coin(self):
        pass

    ## Function Proc_Init_Game
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Init_Game(self):
        pass

    ## Function Proc_Start_Game
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Start_Game(self):
        pass

    ## Function Proc_Start_Ball_Init
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Start_Ball_Init(self):
        pass

    ## Function Proc_Start_Ball_Start
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Start_Ball_Start(self):
        pass

    ## Function Proc_Skillshot
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Skillshot(self):
        pass

    ## Function Proc_Normal_Play_Init
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Normal_Play_Init(self):
        pass

    ## Function Proc_Normal_Play
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Normal_Play(self):
        pass

    ## Function Proc_Choose_Mode_Init
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Choose_Mode_Init(self):
        pass

    ## Function Proc_Choose_Mode
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Choose_Mode(self):
        pass

    ## Function Proc_Mode_Active_Init
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Mode_Active_Init(self):
        pass

    ## Function Proc_Mode_Active
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Mode_Active(self):
        pass

    ## Function Proc_Jpot_Avail_Init
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Jpot_Avail_Init(self):
        pass

    ## Function Proc_Jpot_Avail
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_Jpot_Avail(self):
        pass

    ## Function Proc_End_Of_Ball
    #
    #  @param  self          [in]   Object reference
    #  @return None
    def Proc_End_Of_Ball(self):
        pass

