#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    solBitNames.py
# @author  AutoGenerated
# @date    05/31/2017
#
# @note    Open Pinball Project
# @note    Copyright 2014, Hugh Spahr
#
# @brief These are the solenoid bit names.  It has a bitmask for each solenoid.

#===============================================================================

import rs232Intf

## Solenoid bit name enumeration.
#  Contains a bit mask for each solenoid.  Can also contain bitfield masks.
#  Top most nibble contains the index of the solenoid card base 0.
class SolBitNames:
    def __init__(self):
        pass

    SOL_DROP_BANK                                    = 0x02000001
    SOL_LFT_SLING                                    = 0x02000002
    SOL_BTM_POP                                      = 0x02000004
    SOL_TOP_POP                                      = 0x02000008
    SOL_LFT_POP                                      = 0x02010001
    SOL_SAUCER                                       = 0x02010002
    SOL_OUTHOLE                                      = 0x02010004
    SOL_RGHT_SLING                                   = 0x02010008
    SOL_LFT_FLIPPER                                  = 0x03000001
    SOL_RGHT_FLIPPER                                 = 0x03000002
    SOL_KNOCKER                                      = 0x03000004

    SOL_DROP_BANK_CRD2MSK                            = 0x00000001
    SOL_LFT_SLING_CRD2MSK                            = 0x00000002
    SOL_BTM_POP_CRD2MSK                              = 0x00000004
    SOL_TOP_POP_CRD2MSK                              = 0x00000008
    SOL_LFT_POP_CRD2MSK                              = 0x00000100
    SOL_SAUCER_CRD2MSK                               = 0x00000200
    SOL_OUTHOLE_CRD2MSK                              = 0x00000400
    SOL_RGHT_SLING_CRD2MSK                           = 0x00000800
    SOL_LFT_FLIPPER_CRD3MSK                          = 0x00000001
    SOL_RGHT_FLIPPER_CRD3MSK                         = 0x00000002
    SOL_KNOCKER_CRD3MSK                              = 0x00000004

    ## Solenoid board bit names
    # Indexed into using the [SolBitNames](@ref solBitNames.SolBitNames) class
    SOL_BRD_BIT_NAMES = [ [ ],
        [ ],
        ["DropBank", "LftSling", "BtmPop", "TopPop",
        "LftPop", "Saucer", "Outhole", "RghtSling",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused"],
        ["LftFlip", "RghtFlip", "Knocker", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused"] ]

    ## Solenoid board configuration
    # Three bytes for each solenoid being configured
    SOL_BRD_CFG = [ [ ],
        [ ],
        [rs232Intf.CFG_SOL_AUTO_CLR, '\x38', '\x00', rs232Intf.CFG_SOL_USE_MTRX_AUTO_CLR, '\x14', '\x23',
        rs232Intf.CFG_SOL_USE_MTRX_AUTO_CLR, '\x18', '\x21', rs232Intf.CFG_SOL_USE_MTRX_AUTO_CLR, '\x18', '\x22',
        rs232Intf.CFG_SOL_USE_MTRX_AUTO_CLR, '\x18', '\x20', rs232Intf.CFG_SOL_AUTO_CLR, '\x20', '\x00',
        rs232Intf.CFG_SOL_AUTO_CLR, '\x18', '\x00', rs232Intf.CFG_SOL_USE_MTRX_AUTO_CLR, '\x14', '\x24',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00'],
        [rs232Intf.CFG_SOL_ON_OFF_USE_SW, '\x00', '\x00', rs232Intf.CFG_SOL_ON_OFF_USE_SW, '\x00', '\x00',
        rs232Intf.CFG_SOL_AUTO_CLR, '\x10', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00'] ]

