#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    sounds.py
# @author  AutoGenerated
# @date    05/06/2017
#
# @note    Open Pinball Project
# @note    Copyright 2015, Hugh Spahr
#
# @brief This is an enumeration of all the sounds.

#===============================================================================

## Sounds enumeration.
#  Contains an entry for each sound
class Sounds():
    def __init__(self):
        pass

    SOUND_HELLOBABY                          = 0
    SOUND_BADTARGET1                         = 1
    SOUND_BADTARGET2                         = 2
    SOUND_BALLDRAINNOGOOD                    = 3
    SOUND_CHOOSESINGER                       = 4
    SOUND_SAMMYHAGAR                         = 5
    SOUND_DAVIDLEEROTH                       = 6
    SOUND_RUNNIN_DEVIL                       = 7
    SOUND_GIMME_BREAK                        = 8
    SOUND_HOT_TEACHER1                       = 9
    SOUND_HOT_TEACHER2                       = 10
    SOUND_HOT_TEACHER3                       = 11
    SOUND_PANAMA                             = 12
    SOUND_CHOOSE_JUKEBOX                     = 13

    ## Sound file list
    # Indexed into using the [Sounds](@ref sounds.Sounds) class
    SND_FILES = ["sounds/helloBaby.wav", "sounds/badTarget1.wav", "sounds/badTarget2.wav", "sounds/ballDrainNoGood.wav", "sounds/chooseSinger.wav", 
        "sounds/sammyHagar.wav", "sounds/davidLeeRoth.wav", "sounds/runninDevil.wav", "sounds/gimmeBreak.wav", "sounds/hotTeacherDrums1.wav",
        "sounds/hotTeacherDrums2.wav", "sounds/hotTeacherDrums3.wav", "sounds/panama.wav", "sounds/chooseJukebox.wav"]

