#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    states.py
# @author  AutoGenerated
# @date    04/27/2017
#
# @note    Open Pinball Project
# @note    Copyright 2015, Hugh Spahr
#
# @brief This is an enumeration of all the states.

#===============================================================================

## State enumeration.
#  Contains an entry for each state
class State():
    def __init__(self):
        pass

    MODE_INIT                        = 0
    MODE_ATTRACT                     = 1
    MODE_INIT_GAME                   = 2
    MODE_SKILLSHOT                   = 3
    MODE_NORMAL_PLAY                 = 4
    MODE_CHOOSE_MODE                 = 5
    MODE_MODE_ACTIVE                 = 6
    MODE_JPOT_AVAIL                  = 7
    MODE_ERROR                       = 8
    MODE_TILT                        = 9
    MODE_END_OF_BALL                 = 10


    ## State name strings.
    # Indexed into using [State](@ref states.State) enumeration
    STATE_STR = [ "Init", "Attract", "InitGame", "SkillShot",
        "NormalPlay", "ChooseMode", "ModeActive", "JpotAvail",
        "Error", "Tilt", "EndOfBall" ]

