#config_version=4

#
#===============================================================================
## @mainpage
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#===============================================================================
##
# @file    base.yaml
# @author  Hugh Spahr
# @date    1/8/2016
#
# @note    Open Pinball Project
# @note    Copyright 2016, Hugh Spahr
#
# @brief yaml code for the base mode

#===============================================================================

mode:
  start_events: cmd_end_attract_mode
  priority: 100

slide_player:
  mode_base_started:
    slide_1:
      priority: 10
scoring:
  sharpe_lanes_default_unlit_hit:
    score: 5
  sharpe_lanes_default_lit_hit:
    score: 2
  sharpe_lanes_default_lit_complete:
    score: 50

shot_groups:
  sharpe_lanes:
    rotate_left_events: left_flipper_active
    rotate_right_events: right_flipper_active
    reset_events:
      sharpe_lanes_default_lit_complete: 1s
slides:
  slide_1:
  - type: image
    image: sal_guy
  - type: text
    text: (player1|score)
    style: old_disp
    number_grouping: true
      # Currently setting min digits to 10 since there is no right justification
    min_digits: 10
    x: left+56
    y: top-768
    color: ee9900
    font_size: 64
    anchor_x: left
    anchor_y: top
  - type: text
    text: (player2|score)
    style: old_disp
    number_grouping: true
    min_digits: 10
    x: left+800
    y: top-768
    color: ee9900
    font_size: 64
    anchor_x: left
    anchor_y: top
  - type: text
    text: (player3|score)
    style: old_disp
    number_grouping: true
    min_digits: 10
    x: left+56
    y: top-912
    color: ee9900
    font_size: 64
    anchor_x: left
    anchor_y: top
  - type: text
    text: (player4|score)
    style: old_disp
    number_grouping: true
    min_digits: 10
    x: left+800
    y: top-912
    color: ee9900
    font_size: 64

    anchor_x: left
    anchor_y: top
#sound_player:
#  init_mode:
    # HRS:  This should play good bad and ugly
    #sound: Rookie
    #start_events: mode_base_started

