#config_version=4

#
#===============================================================================
## @mainpage
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#===============================================================================
##
# @file    skillshot.yaml
# @author  Hugh Spahr
# @date    2/23/2016
#
# @note    Open Pinball Project
# @note    Copyright 2016, Hugh Spahr
#
# @brief yaml code for the skillshot mode

#===============================================================================

mode:
  start_events: ball_starting
  stop_events: cmd_end_attract_mode
  priority: 100

slide_player:
  mode_skillshot_started:
    mchncfg_empty_slide:
      priority: 10

sound_player:
  mode_skillshot_started: Rookie
  s_upper_ctr_rollover_active: skillshot_sound_pool

event_player:
  playfield_active:
    cmd_end_attract_mode
  s_upper_ctr_rollover_active:
    skillshot_play_skillshot_made_clip

scoring:
  s_upper_ctr_rollover_active:
    score: 50

show_player:
  mode_skillshot_started:
    skillshot_light_loop:
      loops: -1
      speed: 2         

sound_pools:
   skillshot_sound_pool:
      type: random
      sounds:
         hellOfaShotMister
         niceShootinTex
