#config_version=3

#
#===============================================================================
## @mainpage
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#===============================================================================
##
# @file    skillshot.yaml
# @author  Hugh Spahr
# @date    2/23/2016
#
# @note    Open Pinball Project
# @note    Copyright 2016, Hugh Spahr
#
# @brief yaml code for the skillshot mode

#===============================================================================

mode:
  start_events: ball_starting
  stop_events: cmd_end_attract_mode
  priority: 100

slide_player:
  mode_skillshot_started:
    - type: image
      image: sal_guy
      slide_priority: 10
    - type: text
      text: "%player1|score%"
      font: old_disp
      number_grouping: true
      # Currently setting min digits to 10 since there is no right justification
      min_digits: 10
      x: 56
      y: 768
      color: ee9900
      size: 64
    - type: text
      text: "%player2|score%"
      font: old_disp
      number_grouping: true
      min_digits: 10
      x: 800
      y: 768
      color: ee9900
      size: 64
    - type: text
      text: "%player3|score%"
      font: old_disp
      number_grouping: true
      min_digits: 10
      x: 56
      y: 912
      color: ee9900
      size: 64
    - type: text
      text: "%player4|score%"
      font: old_disp
      number_grouping: true
      min_digits: 10
      x: 800
      y: 912
      color: ee9900
      size: 64

sound_player:
  init_mode:
    sound: Rookie
    start_events: mode_skillshot_started

light_player:
    mode_skillshot_started:
      - show: skillshot_light_loop
        repeat: yes
        tocks_per_sec: 2

event_player:
  playfield_active:
    cmd_end_attract_mode
#  s_upper_rght_rollover_active:
#    cmd_end_attract_mode

scoring:
  s_upper_ctr_rollover_active:
    score: 50
  s_upper_ctr_rollover_active:
    score: 50
