#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    inpBitNames.py
# @author  AutoGenerated
# @date    11/07/2016
#
# @note    Open Pinball Project
# @note    Copyright 2014, Hugh Spahr
#
# @brief These are the input bit names.  It has a bitmask for each input.

#===============================================================================

import rs232Intf

## Input bit name enumeration.
#  Contains a bit mask for each input.  Can also contain bitfield masks.
#  Top most nibble contains the index of the input card base 0.
class InpBitNames:
    def __init__(self):
        pass

    INP_UPPER_RGHT_ROLLOVER          = 0x00040001
    INP_UPPER_CTR_ROLLOVER           = 0x00040002
    INP_UPPER_LFT_ROLLOVER           = 0x00040004
    INP_UPPER_LFT_TOP_TRGT           = 0x00040008
    INP_UPPER_LFT_BTM_TRGT           = 0x00040010
    INP_CTR_RGHT_ROLLOVER            = 0x00040020
    INP_CTR_CTR_ROLLOVER             = 0x00040040
    INP_CTR_LFT_ROLLOVER             = 0x00040080
    INP_UPPER_RUBBER                 = 0x01040001
    INP_SPINNER                      = 0x01040002
    INP_CTR_RGHT_RUBBER              = 0x01040004
    INP_JKPOT_ROLLOVER               = 0x01040008
    INP_BELOW_KICKOUT_RUBBER         = 0x01040010
    SOL_TOP_DROP_RUBBER              = 0x01040020
    INP_DROP_TRGT_1S                 = 0x01080001
    INP_DROP_TRGT_2H                 = 0x01080002
    INP_DROP_TRGT_3O                 = 0x01080004
    INP_DROP_TRGT_4O                 = 0x01080008
    INP_DROP_TRGT_5T                 = 0x01080010
    INP_DROP_TRGT_6E                 = 0x01080020
    INP_DROP_TRGT_7R                 = 0x01080040
    INP_DROP_BANK_MISS               = 0x01080080
    INP_BTM_LFT_INLN_ROLLOVER        = 0x03040001
    INP_BTM_LFT_OUTLN_ROLLOVER       = 0x03040002
    INP_CTR_LOW_ROLLOVER             = 0x03040004
    INP_BTM_RGHT_RUBBER              = 0x03040008
    INP_BTM_RGHT_LOW_RUBBER          = 0x03040010
    INP_SLAM_TILT                    = 0x03080001
    INP_TILT                         = 0x03080002
    INP_COIN_DROP                    = 0x03080004
    INP_START                        = 0x03080008

    ## Input board bit names
    # Indexed into using the [InpBitNames](@ref inpBitNames.InpBitNames) class
    INP_BRD_BIT_NAMES = [ ["Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "UpRghtRoll", "UpCtrRoll", "UpLftRoll", "UpLftTopTrgt",
        "UpLftBtmTrgt", "CtrRghtRoll", "CtrCtrRoll", "CtrLftRoll",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused"],
        ["Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "UpRbr", "Spinner", "CtrRghtRbr", "JkpotRoll",
        "BlwKickRbr", "TopDropRbr", "Unused", "Unused",
        "DrpTrgt1S", "DrpTrgt2H", "DrpTrgt3O", "DrpTrgt4O",
        "DrpTrgt5T", "DrpTrgt6E", "DrpTrgt7R", "DropBnkMiss"],
        [ ],
        ["Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "BtmLftInLnRoll", "BtmLftOutLnRoll", "CtrLowRoll", "BtmRghtRbr",
        "BtmRghtLowRbr", "Unused", "Unused", "Unused",
        "SlamTilt", "Tilt", "CoinDrp", "Start",
        "Unused", "Unused", "Unused", "Unused"] ]

    ## Input board configuration
    INP_BRD_CFG = [ [rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE,
        rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE],
        [rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE,
        rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE,
        rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE],
        [ ],
        [rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE,
        rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE,
        rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE] ]

