#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    inpBitNames.py
# @author  AutoGenerated
# @date    02/08/2015
#
# @note    Open Pinball Project
# @note    Copyright 2014, Hugh Spahr
#
# @brief These are the input bit names.  It has a bitmask for each input.

#===============================================================================

import rs232Intf

## Input bit name enumeration.
#  Contains a bit mask for each input.  Can also contain bitfield masks.
#  Top most nibble contains the index of the input card base 0.
class InpBitNames:
    INP_SPINNER                      = 0x00001
    INP_CTR_RGHT_RUBBER              = 0x00002
    INP_HORSHOE_ROLLOVER             = 0x00004
    INP_BELOW_KICKOUT_RUBBER         = 0x00008
    INP_UPPER_RUBBER                 = 0x00010
    INP_UPPER_RGHT_ROLLOVER          = 0x00020
    INP_UPPER_CTR_ROLLOVER           = 0x00040
    INP_UPPER_LFT_ROLLOVER           = 0x00080
    INP_UPPER_LFT_TOP_TRGT           = 0x00400
    INP_UPPER_LFT_BTM_TRGT           = 0x00800
    INP_CTR_RGHT_ROLLOVER            = 0x02000
    INP_CTR_CTR_ROLLOVER             = 0x04000
    INP_CTR_LFT_ROLLOVER             = 0x08000
    INP_BTM_LFT_INLN_ROLLOVER        = 0x10001
    INP_BTM_LFT_OUTLN_ROLLOVER       = 0x10002
    INP_CTR_LOW_ROLLOVER             = 0x10004
    INP_DROP_BANK_MISS               = 0x10008
    INP_BTM_RGHT_RUBBER              = 0x10010
    INP_BTM_RGHT_LOW_RUBBER          = 0x10020
    INP_SLAM_TILT                    = 0x10040
    INP_START                        = 0x10080
    INP_COIN_DROP                    = 0x10100
    INP_DROP_TRGT_1S                 = 0x10200
    INP_DROP_TRGT_2H                 = 0x10400
    INP_DROP_TRGT_3O                 = 0x10800
    INP_DROP_TRGT_4O                 = 0x11000
    INP_DROP_TRGT_5T                 = 0x12000
    INP_DROP_TRGT_6E                 = 0x14000
    INP_DROP_TRGT_7R                 = 0x18000

    ## Input board bit names
    # Indexed into using the [InpBitNames](@ref inpBitNames.InpBitNames) class
    INP_BRD_BIT_NAMES = [ ["Spinner", "CtrRghtRbr", "HorseRoll", "BlwKickRbr",
        "UpRbr", "UpRghtRoll", "UpCtrRoll", "UpLftRoll",
        "Unused", "Unused", "UpLftTopTrgt", "UpLftBtmTrgt",
        "Unused", "CtrRghtRoll", "CtrCtrRoll", "CtrLftRoll"],
        ["BtmLftInLnRoll", "BtmLftOutLnRoll", "CtrLowRoll", "DropBnkMiss",
        "BtmRghtRbr", "BtmRghtLowRbr", "SlamTilt", "Start",
        "CoinDrp", "DrpTrgt1S", "DrpTrgt2H", "DrpTrgt3O",
        "DrpTrgt4O", "DrpTrgt5T", "DrpTrgt6E", "DrpTrgt7R"] ]

    ## Input board configuration
    INP_BRD_CFG = [ [rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE,
        rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE,
        rs232Intf.CFG_INP_STATE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE],
        [rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE,
        rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE,
        rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE,
        rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE, rs232Intf.CFG_INP_FALL_EDGE] ]

