#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    solBitNames.py
# @author  AutoGenerated
# @date    12/05/2016
#
# @note    Open Pinball Project
# @note    Copyright 2014, Hugh Spahr
#
# @brief These are the solenoid bit names.  It has a bitmask for each solenoid.

#===============================================================================

import rs232Intf

## Solenoid bit name enumeration.
#  Contains a bit mask for each solenoid.  Can also contain bitfield masks.
#  Top most nibble contains the index of the solenoid card base 0.
class SolBitNames:
    def __init__(self):
        pass

    SOL_UPPER_LFT_POP                                = 0x00030001
    SOL_UPPER_CTR_POP                                = 0x00030002
    SOL_DROP_BANK                                    = 0x00030004
    SOL_KICKOUT_HOLE                                 = 0x01010001
    SOL_BTM_LOW_POP                                  = 0x01010002
    SOL_BTM_UP_POP                                   = 0x01010004
    SOL_BTM_LFT_SLING                                = 0x03010001
    SOL_LFT_FLIPPER                                  = 0x03010002
    SOL_BALL_IN_PLAY                                 = 0x03010004
    SOL_RGHT_FLIPPER                                 = 0x03010008

    SOL_UPPER_LFT_POP_CRD0MSK                        = 0x01000000
    SOL_UPPER_CTR_POP_CRD0MSK                        = 0x02000000
    SOL_DROP_BANK_CRD0MSK                            = 0x04000000
    SOL_KICKOUT_HOLE_CRD1MSK                         = 0x00000100
    SOL_BTM_LOW_POP_CRD1MSK                          = 0x00000200
    SOL_BTM_UP_POP_CRD1MSK                           = 0x00000400
    SOL_BTM_LFT_SLING_CRD3MSK                        = 0x00000100
    SOL_LFT_FLIPPER_CRD3MSK                          = 0x00000200
    SOL_BALL_IN_PLAY_CRD3MSK                         = 0x00000400
    SOL_RGHT_FLIPPER_CRD3MSK                         = 0x00000800

    ## Solenoid board bit names
    # Indexed into using the [SolBitNames](@ref solBitNames.SolBitNames) class
    SOL_BRD_BIT_NAMES = [ ["Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "UpLftPop", "UpCtrPop", "DropBank", "Unused"],
        ["Unused", "Unused", "Unused", "Unused",
        "KickOut", "BtmLowPop", "BtmUpPop", "Unused",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused"],
        [ ],
        ["Unused", "Unused", "Unused", "Unused",
        "BtmLftSling", "LftFlip", "BallInPlay", "RghtFlip",
        "Unused", "Unused", "Unused", "Unused",
        "Unused", "Unused", "Unused", "Unused"] ]

    ## Solenoid board configuration
    # Three bytes for each solenoid being configured
    SOL_BRD_CFG = [ [rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_USE_SWITCH, '\x18', '\x00', rs232Intf.CFG_SOL_USE_SWITCH, '\x10', '\x00',
        rs232Intf.CFG_SOL_USE_SWITCH, '\x20', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00'],
        [rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_AUTO_CLR, '\x20', '\x00', rs232Intf.CFG_SOL_USE_SWITCH, '\x10', '\x00',
        rs232Intf.CFG_SOL_USE_SWITCH, '\x10', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00'],
        [ ],
        [rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_USE_SWITCH, '\x10', '\x00', rs232Intf.CFG_SOL_USE_SWITCH, '\x20', '\x04',
        rs232Intf.CFG_SOL_AUTO_CLR, '\x10', '\x00', rs232Intf.CFG_SOL_USE_SWITCH, '\x20', '\x04',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00',
        rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00', rs232Intf.CFG_SOL_DISABLE, '\x00', '\x00'] ]

