#!/usr/bin/env python
#
# Warning - This is an auto-generated file.  All changes to this file will
# be overwritten next time GenPyCode.py is re-run.  Do not change this file
# unless you want to start hand editing the files.
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    timers.py
# @author  AutoGenerated
# @date    02/08/2015
#
# @note    Open Pinball Project
# @note    Copyright 2014, Hugh Spahr
#
# @brief These are the timer names.  The timer names are converted into a
#    bitmask

#===============================================================================

## Timer bit name enumeration.
#  Contains an enumeration for each timer.

class Timers:
    def __init__(self):
        pass
    
    #Used to index into timeouts and grab timeout in ms
    TIMEOUT_OFFSET = 1
    TIMERS_PER_GROUP = 32

    ## Enumeration of timers
    # @Note Must be contiguous starting from 0 since used as index
    TIMEOUT_KICKOUT_TIMER            =  0
    TIMEOUT_BALL_LOCATE              =  1
    TIMEOUT_SPECIAL_TIMER            =  2
    TIMEOUT_RELOAD_TIMER             =  3
    TIMEOUT_RETRY_TIMER              =  4
    TIMEOUT_JACKPOT_TIMER            =  5
    TIMEOUT_DUEL_TIMER               =  6
    TIMEOUT_GENERAL_TIMER            =  7
    TIMEOUT_GALLOP                   =  8
    TIMEOUT_KICKOUT                  =  9

    timeouts = [
        [TIMEOUT_KICKOUT_TIMER, 1000],
        [TIMEOUT_BALL_LOCATE, 5000],
        [TIMEOUT_SPECIAL_TIMER, 30000],
        [TIMEOUT_RELOAD_TIMER, 20000],
        [TIMEOUT_RETRY_TIMER, 3000],
        [TIMEOUT_JACKPOT_TIMER, 30000],
        [TIMEOUT_DUEL_TIMER, 60000],
        [TIMEOUT_GENERAL_TIMER, 10000],
        [TIMEOUT_GALLOP, 3000],
        [TIMEOUT_KICKOUT, 500] ]
