#!/usr/bin/env python
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    imageChains.py
# @author  Hugh Spahr
# @date    6/1/2014
#
# @note    Open Pinball Project
# @note    Copyright 2014, Hugh Spahr
#
# @brief These are the image chains.  It includes chains to automatically change
#    background images depending on the state.

#===============================================================================

from rules.images import Images

## Image chains class.
#
#  Contains all the image chains that are specific to this set of pinball rules.
#  This will eventually be autogenerated by the parser and spit out in this
#  Python form.
#
#  Each image chain group contains the sound to play, the command, and the
#  parameter to the command.
#
#  @note:  Images are only displayed if the command is WAIT or END_CHAIN
class ImageChains():
    # Image chain commands
    WAIT = 0
    REPEAT = 1
    END_CHAIN = 2

    # Offsets into sublist
    IMAGE_OFFSET = 0
    CH_CMD_OFFSET = 1
    PARAM_OFFSET = 2
    
    ## Image chain attract
    ImageAttract = [
        [Images.LEFT_GUY, WAIT, 1000],
        [Images.RIGHT_GUY, WAIT, 1000],
        [Images.LFTCTR_GUY, WAIT, 1000],
        [Images.FULL_BGND, WAIT, 5000],
        [0, REPEAT, 0] ]
