#!/usr/bin/env python
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    ledChains.py
# @author  Hugh Spahr
# @date    5/4/2014
#
# @note    Open Pinball Project
# @note    Copyright 2014, Hugh Spahr
#
# @brief These are the LED chains.  It includes chains to automatically change
#    LEDs depending on the state.

#===============================================================================

from rules.states import State
from rules.ledBitNames import LedBitNames

## LED chains class.
#
#  Contains all the LED chains that are specific this this set of pinball rules.
#  This will eventually be autogenerated by the parser and spit out in this
#  Python form.
#
# @note LEDs only updated when using WAIT command in LED chains
class LedChains():
    # LED chain commands
    WAIT = 0
    REPEAT = 1
    END_CHAIN = 2

    MASK_OFFSET = 0
    CHAIN_OFFSET = 1
    
    # Offsets into sublist
    CH_LED_BITS_OFFSET = 0
    CH_CMD_OFFSET = 1
    PARAM_OFFSET = 2
    
    ## LED Chain attract
    #    - First entry is LED mask
    #    - Next groups have a bitfield of LEDs to change and command
    LedCh_Attract = [ LedBitNames.ALL_BITS_MSK,
        [ [LedBitNames.SPECIAL, WAIT, 500],
          [LedBitNames.LFT_TRGT_1 | LedBitNames.RGHT_TRGT_1, WAIT, 500],
          [LedBitNames.LFT_TRGT_2 | LedBitNames.RGHT_TRGT_2, WAIT, 500],
          [LedBitNames.INLANE_LFT | LedBitNames.INLANE_RGHT, WAIT, 500],
          [LedBitNames.INLANE_CTR, WAIT, 500],
          [0, REPEAT, 0] ] ]
    
    ## LED Chain tilt
    #    - First entry is LED mask
    #    - Next groups have a bitfield of LEDs to change and command
    LedCh_Tilt = [ LedBitNames.ALL_BITS_MSK,
        [ [0, WAIT, 100],
          [0, END_CHAIN] ] ]
