#!/usr/bin/env python
#
#===============================================================================
#
#                           OOOO
#                         OOOOOOOO
#        PPPPPPPPPPPPP   OOO    OOO   PPPPPPPPPPPPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#    PPP          PPP   OOO      OOO   PPP          PPP
#     PPP         PPP   OOO      OOO   PPP         PPP
#      PPPPPPPPPPPPPP   OOO      OOO   PPPPPPPPPPPPPP
#       PPPPPPPPPPPPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP   OOO      OOO   PPP
#                 PPP    OOO    OOO    PPP
#                 PPP     OOOOOOOO     PPP
#                PPPPP      OOOO      PPPPP
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#===============================================================================
##
# @file    soundChains.py
# @author  Hugh Spahr
# @date    5/7/2014
#
# @note    Open Pinball Project
# @note    Copyright 2014, Hugh Spahr
#
# @brief These are the LED chains.  It includes chains to automatically change
#    LEDs depending on the state.

#===============================================================================

from rules.sounds import Sounds

## Sound chains class.
#
#  Contains all the sound chains that are specific this this set of pinball rules.
#  This will eventually be autogenerated by the parser and spit out in this
#  Python form.
#
#  Each sound chain group contains the sound to play, the command, and the
#  parameter to the command.
#
#  @note:  Sounds are only played if the command is WAIT or END_CHAIN
class SoundChains():
    # LED chain commands
    WAIT = 0
    REPEAT = 1
    END_CHAIN = 2

    # Offsets into sublist
    SOUND_OFFSET = 0
    CH_CMD_OFFSET = 1
    PARAM_OFFSET = 2
    
    ## Sound Chain press start
    PressStart = [
        [Sounds.OPEN_DOOR, WAIT, 15000],
        [0, REPEAT, 0] ]
    
    ## Sound Chain tilt
    Tilt = [
        [Sounds.WAH_WUH, END_CHAIN, 0] ]
